#pragma once

#include <cstdint>
#include <string>

namespace hui {

// 4.1 Geometry

struct Point { int x, y; };
struct Size  { int w, h; };
struct Rect  { int x, y, w, h; };

inline Rect rectFromPoints(Point topLeft, Point bottomRight) {
    return { topLeft.x, topLeft.y, bottomRight.x - topLeft.x, bottomRight.y - topLeft.y };
}

inline bool rectContains(Rect r, Point p) {
    return p.x >= r.x && p.x <= r.x + r.w && // Wait, border inclusion
           p.y >= r.y && p.y <= r.y + r.h;
}

inline Rect rectInset(Rect r, int dx, int dy) {
    return { r.x + dx, r.y + dy, r.w - 2 * dx, r.h - 2 * dy };
}

// 4.2 Color

struct Color {
    uint8_t r, g, b, a;

    static constexpr Color white()       { return {255, 255, 255, 255}; }
    static constexpr Color black()       { return {  0,   0,   0, 255}; }
    static constexpr Color transparent() { return {  0,   0,   0,   0}; }

    Color withAlpha(uint8_t newAlpha) const {
        return { r, g, b, newAlpha };
    }

    Color lerp(Color other, float t) const {
        if (t <= 0.0f) return *this;
        if (t >= 1.0f) return other;
        return {
            static_cast<uint8_t>(r + t * (other.r - r)),
            static_cast<uint8_t>(g + t * (other.g - g)),
            static_cast<uint8_t>(b + t * (other.b - b)),
            static_cast<uint8_t>(a + t * (other.a - a))
        };
    }
};

// 0 is the null handle
using FontHandle = uint32_t;
using TextureHandle = uint32_t;

// 4.4 Button Enum

enum class Button : uint8_t {
    Up,
    Down,
    Left,
    Right,
    A,
    B,
    X,
    Y,
    L1,
    L2,
    R1,
    R2,
    Start,
    Select,
    Guide,

    COUNT      // sentinel — do not use as a value
};

static_assert(static_cast<uint8_t>(Button::COUNT) == 15, "Button enum values must not have duplicates or gaps");

// 4.5 Button Events

enum class ButtonEventKind { Down, Up };

struct ButtonEvent {
    Button          button;
    ButtonEventKind kind;
    bool            synthetic = false; // true if generated by KeyRepeatDriver
};

// 13.4 HintEntry

struct HintEntry {
    std::string buttonLabel;  // "A", "B", "L1/R1", "START", etc.
    std::string actionLabel;  // "Play", "Back", "Options"
    bool        hold = false;
    int         sortOrder;    // enforces display ordering
};

// 4.3 Theme

struct Theme {
    Color background;
    Color surface;         // card / list item background
    Color surfaceAlt;      // alternate row tint
    Color accent;          // focus highlight, playing indicator
    Color textPrimary;
    Color textSecondary;
    Color textDisabled;
    Color warning;         // destructive actions
    Color success;
    Color overlay;         // semi-transparent modal background

    // Focus visuals
    Color focusBorderColor;
    int   focusBorderWidth;  // px, typically 2
    Color focusFillColor;    // accent at ~15% alpha

    // Typography
    FontHandle fontBody;     // primary list text
    FontHandle fontSmall;    // secondary / meta text
    FontHandle fontMono;     // optional, for paths and codes
    int fontBodySize;
    int fontSmallSize;
};

} // namespace hui
